---
- hosts: all
  vars:
    http_port: 80
    version: 3
  tasks:
  - name: ensure apache is at the latest version
    apt:
      name: apache2
      state: latest
  - name: write the index page
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
  - name: write the apache config file
    template:
      src: test-site.conf.j2
      dest: /etc/apache2/sites-enabled/test-site.conf
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: apache2
      state: started
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
